Makefile
terraform/iam.tf
terraform/lambda.tf
terraform/outputs.tf

- lambda function for the integration service
- IAM policy
- building and publishing

Phase2: Deployment setup for integrations service

---

lambda/service/authorization/application_authorizer.go
lambda/service/authorization/application_authorizer_test.go
lambda/service/clients/restClient.go
lambda/service/handler/handler.go
lambda/service/handler/handler_test.go
lambda/service/handler/post_integrations_handler.go
lambda/service/handler/router.go
lambda/service/handler/router_test.go
lambda/service/models/integration.go

updates in preparation for demo

---

terraform/data.tf

- adds pennsieve_postgres config to fix build
https://jenkins.pennsieve.cc/job/service-deploy/job/pennsieve-non-prod/job/us-east-1/job/dev-vpc-use1/job/dev/job/integration-service/10/console

adds pennsieve_postgres config

---

lambda/service/clients/restClient.go
lambda/service/handler/post_integrations_handler.go

adds debug statements

---

terraform/iam.tf

updates policy document

---

terraform/lambda.tf

adds ENV variables

---

lambda/service/authorization/application_authorizer.go
lambda/service/authorization/application_authorizer_test.go
lambda/service/clients/restClient.go
lambda/service/handler/handler_test.go
lambda/service/handler/post_integrations_handler.go
lambda/service/handler/router.go
lambda/service/handler/router_test.go
lambda/service/models/integration.go
lambda/service/store/store.go
lambda/service/store/store_test.go
lambda/service/trigger/trigger.go
lambda/service/trigger/trigger_test.go
lambda/service/utils/utils_test.go

- updates payload sent to integration service
- re-instates authorization logic (POST demo)

updates payload and refactors

---

terraform/variables.tf

- adds common tags to variables.tf

adds common_tags

---

terraform/dynamodb.tf

- removes attributes not required for table creation

removes attributes

---

lambda/service/handler/get_integrations_handler.go
lambda/service/models/integration.go

fix: retrieves path param

---

lambda/service/handler/get_integrations_handler.go
lambda/service/store_dynamodb/integration.go
lambda/service/store_dynamodb/store_dynamodb_test.go
lambda/service/trigger/trigger.go

- refactors GET and POST handlers

fix: refactors GET and POST

---

terraform/lambda.tf

updates timeout

---

lambda/service/trigger/trigger.go

more debug statements

---

lambda/service/handler/handler.go

- debug lambda internet access

debug internet access

---

lambda/service/clients/restClient.go
lambda/service/handler/handler.go
lambda/service/handler/post_integrations_handler.go
lambda/service/trigger/trigger.go

reverts debug code

---

lambda/service/handler/get_integrations_handler.go
lambda/service/handler/handler_test.go
lambda/service/handler/post_integrations_handler.go
lambda/service/handler/router.go

- removes more logging and reinstates authorization

removes more logging and reinstates authorization

---

lambda/service/authorization/application_authorizer.go
lambda/service/authorization/application_authorizer_test.go

- authorizer caters for GET requests

authorizer caters for GET requests

---

README.md
docker-compose.test.yml
lambda/service/authorization/application_authorizer.go
lambda/service/docker-compose.yml
lambda/service/handler/router_test.go
lambda/service/models/integration.go
lambda/service/store/store_test.go
lambda/service/store/test_store.go
lambda/service/utils/utils_test.go

Addresses: https://app.clickup.com/t/8685jyg52
**RISK: LOW**
- updates README.md
- updates tests and fixes flaky tests

fix: refactor tests

---

lambda/service/store_dynamodb/integration.go
lambda/service/store_dynamodb/store_dynamodb_test.go
lambda/service/trigger/trigger.go

Related: https://app.clickup.com/t/8686wy7vh
RISK: **LOW**
- persists params to be used within external application

feature: allow user defined parameters to be passed to external application

---

lambda/service/clients/computeRestClient.go
lambda/service/compute_trigger/compute_payload.go
lambda/service/compute_trigger/compute_trigger.go
lambda/service/compute_trigger/compute_trigger_test.go
lambda/service/handler/get_integrations_handler.go
lambda/service/handler/handler.go
lambda/service/handler/post_workflows_handler.go
lambda/service/models/integration.go
lambda/service/store_dynamodb/integration.go

feature: adds workflows endpoint

---

lambda/service/handler/get_integrations_handler.go
lambda/service/handler/router.go
lambda/service/models/integration.go

- explicit application params in integration

fix: explicit application params in integration

---

lambda/service/handler/get_integrations_handler.go
lambda/service/handler/post_integrations_handler.go
lambda/service/models/integration.go

- fix to support backward compatibility

fix: GET endpoint

---

lambda/service/compute_trigger/compute_trigger.go
lambda/service/handler/handler.go
lambda/service/handler/put_integrations_handler copy.go
lambda/service/handler/router.go
lambda/service/mocks/mocks.go
lambda/service/models/integration.go
lambda/service/store_dynamodb/integration.go
lambda/service/store_dynamodb/store_dynamodb.go
lambda/service/store_dynamodb/store_dynamodb_test.go

- adds PUT /integrations endpoint - this will allow us to update an integration, for example to update that it has completed.

feature: adds PUT integrations endpoint

---

lambda/service/handler/get_integration_handler.go
lambda/service/mappers/mappers.go

- surfaces dates in GET endpoints

fix: surfaces dates

---

lambda/service/handler/router.go

fix: updates router

---

lambda/service/handler/handler_test.go

fix: fixes tests

---

lambda/service/handler/handler.go
lambda/service/handler/post_workflow_instances_handler.go
lambda/service/handler/put_workflow_instances_handler.go

- adds POST and PUT /workflows/instances

feature: adds POST and PUT /workflows/instances

---

lambda/service/handler/get_workflow_instance_handler.go

- updates get workflow instance logic

fix: updates get workflow instance logic

---

README.md
lambda/service/authorization/application_authorizer.go
lambda/service/compute_trigger/compute_trigger.go
lambda/service/compute_trigger/compute_trigger_test.go
lambda/service/go.mod
lambda/service/go.sum
lambda/service/handler/get_integration_handler.go
lambda/service/handler/get_integrations_handler.go
lambda/service/handler/get_workflow_instance_handler.go
lambda/service/handler/get_workflow_instances_handler.go
lambda/service/handler/post_integrations_handler.go
lambda/service/handler/post_workflow_instances_handler.go
lambda/service/handler/post_workflows_handler.go
lambda/service/handler/put_integrations_handler.go
lambda/service/handler/put_workflow_instances_handler.go
lambda/service/mappers/mappers.go
lambda/service/mocks/mocks.go
lambda/service/models/workflow.go
lambda/service/store_dynamodb/store_dynamodb.go
lambda/service/store_dynamodb/store_dynamodb_test.go
lambda/service/store_dynamodb/workflow.go
lambda/service/store_dynamodb/workflow_instance.go
lambda/service/store_dynamodb/workflow_store_dynamodb.go
lambda/service/store_dynamodb/workflow_store_dynamodb_test.go
lambda/service/trigger/trigger.go
lambda/service/trigger/trigger_test.go
terraform/dynamodb.tf
terraform/iam.tf
terraform/lambda.tf

- implements `POST /workflows`
- adds workflows table, database related helpers (for insert and read from workflows table) and tests
- refactors existent tests
- updates terraform
- expands on the concept of workflow instances and removes more "integrations" references

feature: implement POST workflows

---

lambda/service/credentials_retriever/credentials_retriever.go

fix: adds logging

---

lambda/service/credentials_retriever/credentials_retriever.go
terraform/iam.tf

- explicit region and permissions

fix: explicit region and permissions

---

terraform/iam.tf

fix: adds pass role permission

---

lambda/service/clients/computeRestClient.go

fix: updates signing logic

---

lambda/service/clients/computeRestClient.go

fix: more signing changes

---

lambda/service/clients/computeRestClient.go

fix: adds more logging

---

lambda/service/clients/computeRestClient.go
lambda/service/credentials_retriever/credentials_retriever.go
lambda/service/handler/get_workflow_logs_handler.go
lambda/service/handler/post_workflow_instances_handler.go

fix: refactor

---

lambda/service/clients/computeRestClient.go

- new sts client and new signer

fix: new sts client and new signer

---

lambda/service/clients/computeRestClient.go
lambda/service/handler/get_workflow_logs_handler.go
lambda/service/handler/post_workflow_instances_handler.go

- start a workflow instance via IAM

fix: IAM supported starting of a workflow instance

---

lambda/service/compute_trigger/compute_trigger.go
lambda/service/handler/post_workflow_instances_handler.go

- logging for post workflow instance

fix: logging for post workflow instance

---

lambda/service/handler/get_workflow_logs_handler.go
lambda/service/handler/post_workflow_instances_handler.go
lambda/service/store_dynamodb/node.go
lambda/service/store_dynamodb/node_store_dynamodb.go
terraform/data.tf
terraform/iam.tf
terraform/lambda.tf

- refactors to fetch accountId from compute nodes table

fix: refactors to fetch accountId from compute nodes table

---

lambda/service/store_dynamodb/store_dynamodb.go
terraform/lambda.tf

- adds logging and uses legacy mode for compute node interactions

fix: adds logging and uses legacy mode for compute node interactions

---

lambda/service/store_dynamodb/store_dynamodb.go

fix: refactors to add pagination

---

lambda/service/dag/dag.go
lambda/service/dag/dag_sort.go
lambda/service/dag/dag_test.go

- maps processors to DAG
- sorts DAG
- tests

feature: DAG implementation and sorting

---

lambda/service/dag/dag.go
lambda/service/mappers/mappers.go
lambda/service/models/workflow.go
lambda/service/store_dynamodb/workflow.go

fix: reverts previous changes

---

lambda/service/compute_trigger/compute_trigger.go
lambda/service/handler/post_workflow_instances_handler.go
lambda/service/handler/put_workflow_instance_processor_status_handler.go

- put processor status for named workflows logic changed to support workflowUuid(s)

fix: put processor status for named workflows

---

lambda/service/compute_trigger/compute_trigger.go
lambda/service/handler/get_workflow_instance_handler.go

- return execution order for single instance

fix: return execution order for single instance

---

lambda/service/compute_trigger/compute_trigger.go

fix: fixes logic

---

lambda/service/handler/errors.go
lambda/service/handler/handler.go
lambda/service/handler/post_workflow_instances_handler.go
lambda/service/handler/post_workflows_handler.go
lambda/service/handler/put_integrations_handler.go
lambda/service/handler/put_workflow_handler.go
lambda/service/handler/put_workflow_instance_processor_status_handler.go
lambda/service/handler/put_workflow_instance_status_handler.go
lambda/service/handler/put_workflow_instances_handler.go
lambda/service/mappers/mappers.go
lambda/service/mocks/mocks.go
lambda/service/models/workflow.go
lambda/service/store_dynamodb/workflow.go
lambda/service/store_dynamodb/workflow_store_dynamodb.go
lambda/service/store_dynamodb/workflow_store_dynamodb_test.go

- Adds PUT /workflows/{uuid} endpoint - for setting workflow to active or inactive (`isActive = true|false`)

feature: adds PUT endpoint

---

lambda/service/compute_trigger/compute_trigger.go
lambda/service/handler/put_workflow_instance_processor_status_handler.go
lambda/service/mappers/mappers.go
lambda/service/mocks/mocks.go
lambda/service/store_dynamodb/application_store_dynamodb.go
lambda/service/store_dynamodb/application_store_dynamodb_test.go

- filter applications by org (for cases where the same application is deployed in different orgs)

fix: filter applications by org

---

lambda/service/handler/post_workflows_handler.go
lambda/service/mocks/mocks.go
lambda/service/store_dynamodb/workflow_store_dynamodb.go
lambda/service/store_dynamodb/workflow_store_dynamodb_test.go

- returns created workflow on POST
Related PR: https://app.clickup.com/t/868fkyckj

fix: returns created workflow on POST
